server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: "bank-cards-service"

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: user
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:db//migration/changelog/db.changelog-master.yaml

jwt:

  private-key: classpath:${JWT_PRIVATE_KEY:jwt/app.key}
  public-key: classpath:${JWT_PUBLIC_KEY:jwt/app.pub}
  ttl: ${JWT_TTL:120m}

app:
  cors:
    allowed-origins: http://localhost:3000
    allowed-methods: GET,POST,PUT,DELETE
    allowed-headers: Authorization,Content-Type
    allow-credentials: true


logging:
  level:
    org:
      springframework:
        security: debug
        web: debug
        data: debug
